### ISSUE TITLE
你好，请问方便分享工大ICS的课程PPT吗？

### ISSUE THREAD

**Issue by Jiangmmh** [cuttingedge191/HITCS-ICS_CSAPP#1]
repo主你好，我准备报考工大的研究生，而CSAPP内容为专业课重要考点，如果方便的话，能否分享一下今年ICS课程的PPT呢，感激不尽，叨扰。

**Comment by cuttingedge191** [comment]
你好，GitHub上有一些18级学长上传了工大2019年计算机系统课程的课件。由于我们19级是工大首届大类招生，2020年并没有安排计算机系统课程，今年的课件与2019年的差异不大。因此我建议参考2019年的课件。
我个人目前没有整理上传今年课件的计划。

**Comment by cuttingedge191** [comment]
我的一位同学上传了历年期末试题和今年的课件，附链接：
[https://github.com/FuLucas/CSAPP/](https://github.com/FuLucas/CSAPP/)

**Comment by Jiangmmh** [comment]
感谢你的慷慨帮助，祝学业顺利。
